version: '3.3'
services:
  wrapper:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: mapotempo/geocoder-wrapper:${MAPOTEMPO_VERSION:-57.0.0}
    ports:
      - "8081:80" # HOST:CONTAINER, edit only HOST part
    volumes:
        - ./production.rb:/srv/app/config/environments/production.rb
        - ./access.rb:/srv/app/config/access.rb
        - ./poly:/srv/app/poly
    restart: always
    links:
      - redis-cache
      - redis-count
      - addok-fr
      - addok-lu
    environment:
      APP_ENV: production # Swith to "development" for more traces
      REDIS_HOST: redis-cache
      REDIS_COUNT_HOST: redis-count

  redis-cache:
    image: redis:${REDIS_VERSION:-3.2-alpine}
    command: redis-server --save ""

  redis-count:
    image: redis:${REDIS_VERSION:-3.2-alpine}
    volumes:
      - ./data-count:/data
    command: redis-server --appendonly yes

  # France

  addok-fr:
    build: addok
    image: mapotempo/addok:${ADDOK_VERSION:-1.0.2}-${ADDOK_VERSION_BUILD:-1}
    links:
      - redis-server-fr
    volumes:
      - ./addok-fr.conf:/etc/addok/addok.conf
      - ./addresses-fr:/addresses

  redis-server-fr:
    image: redis:${REDIS_VERSION:-3.2-alpine}
    volumes:
      - ./data-fr:/data
    command: redis-server --save ""

  # Luxemburg

  addok-lu:
    build: addok
    image: mapotempo/addok:${ADDOK_VERSION:-1.0.2}-${ADDOK_VERSION_BUILD:-1}
    links:
      - redis-server-lu
    volumes:
      - ./addok-lu.conf:/etc/addok/addok.conf
      - ./addresses-lu:/addresses

  redis-server-lu:
    image: redis:${REDIS_VERSION:-3.2-alpine}
    volumes:
      - ./data-lu:/data
    command: redis-server --save ""
