version: '3.7'
services:
  api:
    image: ${REGISTRY}mapotempo-${EDT:-ce}/geocoder-api:${GEOCODER_VERSION:-latest}
    ports:
      - 8558:8558
    volumes:
      - ./production.rb:/srv/app/config/environments/production.rb
      - ./access.rb:/srv/app/config/access.rb
      - ./poly:/srv/app/poly
    deploy:
      update_config:
        order: start-first
      restart_policy:
        condition: any
    environment:
      APP_ENV: production # Swith to "development" for more traces
      REDIS_HOST: redis-cache
      REDIS_COUNT_HOST: redis-count
    networks:
      - base
      - addok_fr
      - addok_lu
      - redis_cache

  redis-cache:
    image: redis:${REDIS_VERSION:-3.2-alpine}
    command: redis-server --save ""
    deploy:
      restart_policy:
        condition: any
    networks:
      - redis_cache

  redis-count:
    image: redis:${REDIS_VERSION:-3.2-alpine}
    volumes:
      - ./data-count:/data
    command: redis-server --appendonly yes

  # France
  addok-fr:
    image: ${REGISTRY}mapotempo/addok:${ADDOK_VERSION:-1.1.0-rc1}
    volumes:
      - /srv/docker-data/geocoder-api/addok-fr.conf:/etc/addok/addok.conf
      - /srv/docker-data/geocoder-api/addresses-fr:/addresses
    deploy:
      update_config:
        order: start-first
      restart_policy:
        condition: any
    networks:
      - addok_fr
      - redis_server_fr

  redis-server-fr:
    image: redis:${REDIS_VERSION:-3.2-alpine}
    volumes:
      - /srv/docker-data/geocoder-api/data-fr:/data
    command: redis-server --save ""
    deploy:
      restart_policy:
        condition: any
    networks:
      - redis_server_fr

  # Luxemburg
  addok-lu:
    image: ${REGISTRY}mapotempo/addok:${ADDOK_VERSION:-1.1.0-rc1}
    volumes:
      - /srv/docker-data/geocoder-api/addok-lu.conf:/etc/addok/addok.conf
      - /srv/docker-data/geocoder-api/addresses-lu:/addresses
    deploy:
      update_config:
        order: start-first
      restart_policy:
        condition: any
    networks:
      - addok_lu
      - redis_server_lu

  redis-server-lu:
    image: redis:${REDIS_VERSION:-3.2-alpine}
    volumes:
      - /srv/docker-data/geocoder-api/data-lu:/data
    command: redis-server --save ""
    deploy:
      restart_policy:
        condition: any
    networks:
      - redis_server_lu

networks:
  redis_cache:
  addok_fr:
  redis_server_fr:
  addok_lu:
  redis_server_lu:
  base:
    external: ${EXTERNAL_NETWORK:-false}
    driver: overlay
